### PR TITLE
Move repo to codeclimate-community

### PR DESCRIPTION
**Pull request by maxjacobson**

### CODE REVIEW

**Comment by maxjacobson** [comment]
Sigh, I can't enable PR integration now 😞

**Comment by wfleming** [comment]
Should we update the record on codeclimate.com to point to the new URL? 
Or add/remove the repo so the info is correct?

**Comment by maxjacobson** [comment]
I added this as a second cc repo rather than renaming the existing cc repo... so now we have two:
- https://codeclimate.com/github/codeclimate/codeclimate-markdownlint/
- https://codeclimate.com/github/codeclimate-community/codeclimate-markdownlint

I probably should've just renamed the first one but now we're in this boat. Hmm.

**Comment by wfleming** [comment]
And we _also_ still have 
https://codeclimate.com/github/jpignata/codeclimate-markdownlint/

**Comment by maxjacobson** [comment]
And (if were regular users) we can't delete that. Hmm. Very hmm.

**Pull request merged**
